# 设置端口号
server:
  port: 8110
# 设置服务名
spring:
  application:
    name: service-edu
  # 数据库连接
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/guli_edu?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 设置时区和日期格式
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 关闭spring banner
  main:
    banner-mode: off

# mybatis-plus日志开启
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false  # 取消mp的banner图标