server:
  port: 8170 # 服务端口
spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-trade # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
#        ip:
  servlet:
    multipart:
      max-file-size: 512MB # 最大上传单个文件大小：默认1M
      max-request-size: 512MB # 最大置总上传的数据大小 ：默认10M
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/guli_trade?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    port: 6379
    database: 0
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-wait: -1ms
        max-active: 20
    host: 192.168.6.100
  rabbitmq:
    host: 192.168.6.100
    port: 5672
    username: admin
    password: admin
    virtual-host: /admin
    publisher-returns: true
    publisher-confirm-type: simple
logging:
  level:
    root: info
ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000
feign:
  sentinel:
    enabled: true  # 启用feign对sentinel的支持。本质就是sentinel使用动态代理 代理feign客户端
wx:
  pay:
    appid: wxf913bfa3a2c7eeeb
    mchid: 1543338551   # 商户号
    partnerkey: atguigu3b0kn9g5vAtGuifHQH7X8rKCL   # 秘钥：加签验签使用
    notifyurl: http://ls074ejc73x7.ngrok.xiaomiqiu123.top/api/trade/wx/callback   # 支付成功的回调地址
