server:
  port: 8160 #配置启动端口

spring:
  application:
    # 配置服务名
    name: service-ucenter
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  profiles:
    # 配置启动环境
    active: dev
  main:
    banner-mode: off # 关闭bunner
  cloud:
    # nacos配置
    nacos:
      discovery:
        server-addr: localhost:8848
#  redis
  redis:
    port: 6379
    host: 192.168.6.100
#    lettuce:
#      pool:
#        max-active: 20
#        max-wait: -1
#        max-idle: 8
#        min-idle: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_ucenter?serverTimezone=GMT%2B8
    password: root
    username: root


# 配置阿里云sms服务参数
aliyun:
  sms:
    host: "http://dingxin.market.alicloudapi.com"
    path: "/dx/sendSms"
    method: "POST"
    appcode: "8e45699f00ff4bdbb807664045acd813"
    tplId: "TP1711063"
# mybatis-plus
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #mybatis日志
  mapper-locations: classpath:com/service/*/mapper/xml/*.xml