server:
  port: 8120 #配置启动端口

spring:
  application:
    # 配置服务名
    name: service-oss
  profiles:
    # 配置启动环境
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB # 单个文件上传大小限制
      max-request-size: 100MB # 多个文件上传大小限制

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC  # GMT+8


  main:
    banner-mode: off # 关闭bunner
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

# 配置阿里云OSS服务路径
aliyun:
  oss:
    endpoint: https://oss-cn-shanghai.aliyuncs.com
    accessKeyId: your accessKeyId
    accessKeySecret: your accessKeySecret
    bucketName: xxguli-file
